<?php

namespace AppBundle\Repository;

/**
 * CommentProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentProfRepository extends \Doctrine\ORM\EntityRepository
{
}
