<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
    public function findNonAffecter()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.id','e.nomEtudiant','e.prenomEtudiant','e.mailEtudiant','e.telEtudiant');
        $qb->leftJoin('AppBundle:Propositions','p', 'WITH', 'e.id = p.codeEtudiant');
        $qb->addSelect('p');
        $qb->where('p.codeEtudiant IS NULL');
        $qb->addOrderBy('e.nomEtudiant', 'ASC');
        $qb->addOrderBy('e.prenomEtudiant', 'ASC');
        $query = $qb->getQuery();
        $etudiants = $query->getResult();

        return $etudiants;
    }
}
