<?php

namespace AppBundle\Repository;

/**
 * GroupesLdapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesLdapRepository extends \Doctrine\ORM\EntityRepository
{
}
