<?php

namespace AppBundle\Repository;

/**
 * RolesProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesProfRepository extends \Doctrine\ORM\EntityRepository
{
}
