# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Etudiant:
            algorithm: bcrypt
        AppBundle\Entity\Professeur:
            algorithm: bcrypt
        AppBundle\Entity\Contacts:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        etu_db:
            entity:
                class: AppBundle\Entity\Etudiant
                property: userEtudiant
        prof_db:
            entity:
                class: AppBundle\Entity\Professeur
                property: userProf
        contact_db:
            entity:
                class: AppBundle\Entity\Contacts
                property: userContact

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~